name: accordion
description: An expandable Flutter widget list where each item can be expanded or collapsed simply by clicking on the header.
version: 2.1.0
homepage: https://www.vulcansoft.com
repository: https://github.com/GotJimmy/accordion

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.4"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  scroll_to_index: ^2.0.0

flutter:
  uses-material-design: true
